name: dimsim-dev
channels:
  - conda-forge
dependencies:
  - python =3.11
  - pip

  # Base dependencies
  - pydantic >=2.0
  - pyyaml

  # Core dependencies
  - openff-toolkit >=0.18
  - openff-interchange >=0.5
  - openff-nagl-models
  - openff-nagl-base
  - openmm
  - openmmtools
  - sqlmodel
  - rdkit =2023

  - pytorch
  - smee
  - descent

  - pytorch
  - smee
  - descent

  # Development and testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-randomly

  # Documentation
  - sphinx
  - sphinx-rtd-theme
  - sphinx-autodoc-typehints

  # distributed
  - dask
  - dask-jobqueue
  - dask-kubernetes
  - distributed
