name: dimsim-dev
channels:
  - conda-forge
dependencies:
  - python >=3.10
  - pip

  # Base dependencies
  - pydantic >=2.0
  - pyyaml

  # Core dependencies
  - openff-toolkit
  - openff-nagl-models
  - openff-nagl-base
  - openmm
  - openmmtools
  - sqlmodel
  - rdkit

  - pytorch
  - smee
  - descent

  # Development and testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-randomly

  # Documentation
  - sphinx
  - sphinx-rtd-theme
  - sphinx-autodoc-typehints

  # distributed
  - dask
  - dask-jobqueue
  - dask-kubernetes
  - distributed

  # Documentation dependencies
  - sphinx >=4.5,<5
  - nbsphinx
  - sphinx-notfound-page
  - sphinxcontrib-bibtex
  - pandoc
  - ipython

  - pip:
    - git+https://github.com/openforcefield/openff-sphinx-theme.git@main
